language: python

notifications:
  email:
    - alkemic7+travis-ci-notifications@gmail.com

python:
  - "2.5"
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
