language: python

notifications:
  email:
    - alkemic7+travis-ci-notifications@gmail.com

python:
  - "2.6"
  - "2.7"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  - sqlite3 --version
  - pip install pysqlite
  - python -c "import sqlite3; print sqlite3.version"
  - python -c "import django; print django.get_version()"

script:
  - coverage run manage.py test

after_success:
  - coveralls